# 이 설정 파일은 GitHub Actions 워크플로우에서 브랜치를 자동으로 생성하고 관련 작업을 처리하는 방법을 정의합니다.

# 생성될 브랜치의 이름을 정의합니다. 여기서는 이슈 번호를 브랜치 이름으로 사용합니다.
branchName: '${issue.number}'

# 새로운 브랜치가 파생될 기본 브랜치를 지정합니다.
defaultBranch: 'develop'

# 다양한 유형의 브랜치에 대한 설정을 정의합니다.
branches:
  # 'hotfix' 라벨이 있는 이슈에 대한 브랜치 설정
  - label: 'hotfix'   # GitHub 이슈에 적용되는 라벨입니다.
    prefix: 'hotfix/' # 생성될 브랜치 이름의 접두사입니다 (예: hotfix/123).
    name: 'master'    # 이 브랜치가 파생될 대상 브랜치입니다.

  # 'feature' 라벨이 있는 이슈에 대한 브랜치 설정
  - label: 'feature'
    prefix: 'feature/'
    name: 'develop'

  # 'docs' (문서) 라벨이 있는 이슈에 대한 브랜치 설정
  - label: 'docs'
    prefix: 'docs/'
    name: 'develop'

  # 'test' 라벨이 있는 이슈에 대한 브랜치 설정
  - label: 'test'
    prefix: 'test/'
    name: 'develop'

  # 'fix' (버그 수정) 라벨이 있는 이슈에 대한 브랜치 설정
  - label: 'fix'
    prefix: 'fix/'
    name: 'develop'

  # 'enhancement' (기능 개선) 라벨이 있는 이슈에 대한 브랜치 설정
  - label: 'enhancement'
    prefix: 'enhancement/'
    name: 'develop'

# 브랜치가 성공적으로 생성된 후 이슈에 남길 댓글 메시지입니다.
# `${branchName}`은 실제 브랜치 이름으로, `${issue.title}`은 이슈 제목으로 대체됩니다.
commentMessage: '🌱 브랜치 `${branchName}`가 생성되었습니다. 이슈: ${issue.title}'

# 생성된 브랜치에 대한 드래프트(초안) Pull Request를 자동으로 열지 여부를 결정합니다.
# `false`로 설정하면 드래프트 PR을 열지 않습니다.
openDraftPR: false

# 브랜치 생성 후 해당 이슈를 자동으로 닫을지 여부를 결정합니다.
# `true`로 설정하면 이슈를 닫습니다.
autoCloseIssue: true

# 이슈에 있는 라벨을 생성된 Pull Request에 복사할지 여부를 결정합니다.
# `true`로 설정하면 라벨을 복사합니다.
copyIssueLabelsToPR: true

# 이슈에 할당된 담당자를 생성된 Pull Request에 복사할지 여부를 결정합니다.
# `true`로 설정하면 담당자를 복사합니다.
copyIssueAssigneeToPR: true

# 이슈에 설정된 마일스톤을 생성된 Pull Request에 복사할지 여부를 결정합니다.
# `true`로 설정하면 마일스톤을 복사합니다.
copyIssueMilestoneToPR: true