 spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SE_webserver_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mmsdud00!!
    #url: jdbc:h2:tcp://localhost/~/querydsl
    #driver-class-name: org.h2.Driver
    #username: sa
    #password:

  jpa:
    hibernate:
      ddl-auto: update # 설정 변경 가능
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    #database-platform: org.hibernate.dialect.H2Dialect